# Generated by Django 3.2 on 2022-07-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
